# Site settings
title: Random short posts
email: ben.s.kuhn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I write things that are too short, shallow, or incomplete, or
  un-proofread to post to my main blog. For better writing, visit
  http://www.benkuhn.net/.
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 10
url: "http://scraps.benkuhn.net" # the base hostname & protocol for your site
twitter_username: benskuhn
github_username:  benkuhn

# Build settings
markdown: kramdown
